name: example_architecture
description: An example project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Languages
  easy_localization: ^3.0.3

  # Model
  get_it: ^7.6.4
  injectable: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Data
  dio: ^5.3.2
  retrofit: ^4.0.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.1

  # UI
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  infinite_scroll_pagination: ^4.0.0
  shimmer: ^3.0.0
  extended_image: ^8.1.1


  # Firebase
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5

  # Utils
  logger: ^2.0.2
  collection: ^1.17.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  rxdart: ^0.27.7

  # Route
  auto_route: ^6.0.0+1

  # Libs
#  andpad_auth:
#    git:
#      url: git@github.com:88labs/andpad-auth-flutter.git
#      ref: v1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

  auto_route_generator: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.2
  retrofit_generator: ^7.0.8
  flutter_gen_runner: ^5.3.1
  injectable_generator: ^2.4.0

  # Test
  mockito: ^5.4.2
  http_mock_adapter: ^0.6.0
  mocktail_image_network: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Hiragino-Kaku-Gothic-Pro
      fonts:
        - asset: assets/fonts/Hiragino-Kaku-Gothic-Pro-W3.otf
          weight: 300
        - asset: assets/fonts/Hiragino-Kaku-Gothic-Pro-W6.otf
          weight: 600
    - family: Hiragino-Sans
      fonts:
        - asset: assets/fonts/Hiragino-Sans-W3.ttc
          weight: 300
        - asset: assets/fonts/Hiragino-Sans-W4.ttc
          weight: 400
        - asset: assets/fonts/Hiragino-Sans-W6.ttc
          weight: 600
        - asset: assets/fonts/Hiragino-Sans-W7.ttc
          weight: 700

flutter_gen:
  integrations:
    flutter_svg: true
